//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("FoodNutritionApp")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0+85640047e89c63c9767cade1c62e213eb08af5bf")]
[assembly: System.Reflection.AssemblyProductAttribute("FoodNutritionApp")]
[assembly: System.Reflection.AssemblyTitleAttribute("FoodNutritionApp")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")]
[assembly: System.Runtime.Versioning.TargetPlatformAttribute("Android36.0")]
[assembly: System.Runtime.Versioning.SupportedOSPlatformAttribute("Android21.0")]

// Generated by the MSBuild WriteCodeFragment class.

